---
name: "Build Release"

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ps4sdk .
      - name: List build output
        run: docker run --rm --entrypoint "" ps4sdk ls -l /lib/ps4-payload-sdk/libPS4
      - name: Create container
        run: docker create --name ps4sdk_container ps4sdk
      - name: Copy SDK from container
        run: docker cp ps4sdk_container:/lib/ps4-payload-sdk/libPS4/libPS4.a ./libPS4/libPS4.a
      - name: Remove container
        run: docker rm ps4sdk_container
      - name: Create SDK zip archive
        run: |
          zip -r ps4-payload-sdk.zip libPS4 README.md Dockerfile entrypoint.sh
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          artifacts: "ps4-payload-sdk.zip"
