---
name: "Sanity Check"

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ps4sdk .
      - name: List build output
        run: docker run --rm --entrypoint "" ps4sdk ls -l /lib/ps4-payload-sdk/libPS4
